name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger workflow on push to 'main' branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull request to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Use the latest version of actions/checkout

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Use the latest version of setup-buildx-action

    - name: Cache Docker layers
      uses: actions/cache@v3  # Use the latest version of actions/cache
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ github.ref }}-
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Docker login action
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # GitHub secret for Docker username
        password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub secret for Docker password

    - name: Build and push Docker image
      uses: docker/build-push-action@v3  # Use the latest version of build-push-action
      with:
        context: .
        file: ./Dockerfile  # Path to Dockerfile
        push: true  # Push the image to Docker Hub
        tags: ${{ secrets.DOCKER_USERNAME }}/ci-cd-github-actions-docker:latest  # Docker Hub repository

    - name: Deploy to Production (Optional)
      run: |
        echo "Deploying to your production server"
        # Add your deploy script here (e.g., SSH into a server and run deployment commands)
