name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # This triggers the workflow when code is pushed to the 'main' branch
  pull_request:
    branches:
      - main  # This triggers the workflow when a pull request is made to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu for the CI environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Check out the repository code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Set up Docker Buildx for building images

    - name: Cache Docker layers
      uses: actions/cache@v2  # Cache Docker layers to speed up future builds
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and push Docker image
      uses: docker/build-push-action@v2  # Build and push the Docker image
      with:
        context: .
        file: ./Dockerfile  # Path to your Dockerfile
        push: true  # Set this to true to push the image to Docker Hub
        tags: ${{ secrets.DOCKER_USERNAME }}/ci-cd-github-actions-docker:latest  # Replace with your Docker Hub repository name

    - name: Deploy to Production (Optional)
      run: |
        echo "Deploying to your production server"
        # Add your deploy script here (e.g., SSH into a server and run deployment commands)
